# Generated by Django 5.0.6 on 2024-07-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
